// Generated by Bisonc++ V4.01.00 on Tue, 18 Mar 2014 19:13:24 +0100

#ifndef Parser_h_included
#define Parser_h_included

#include <iostream>
#include <sstream>

#include "semantics.h"
#include "Parserbase.h"
#include "FlexLexer.h"

#undef Parser
class Parser : public ParserBase {
public:
 	Parser(std::istream& in) : flagCounter(0), lexer(&in, &std::cerr) {}
	int parse();

private:
	unsigned flagCounter;

	typedef std::map<std::string, VariableData> SymbolTable;
	SymbolTable symbolTable;

	void declareVariable(const std::string& variableName, VariableType type, int row);

	void checkBoolOperator(VariableType type);
	void checkBoolBoolOperator(VariableType type1, VariableType type2);
	void checkBoolUnsignedOperator(VariableType type1, VariableType type2);
	void checkUnsignedUnsignedOperator(VariableType type1, VariableType type2);

	std::string getNextFlag();

	yyFlexLexer lexer;
	void error(char const *msg);	// called on (syntax) errors
	int lex();					  // returns the next token from the
									// lexical scanner.
	void print();				   // use, e.g., d_token, d_loc

	// support functions for parse():
	void executeAction(int ruleNr);
	void errorRecovery();
	int lookup(bool recovery);
	void nextToken();
	void print__();
};


#endif
